services:
  mosquitto-3:
    image: eclipse-mosquitto:2.0.17
    container_name: mosquitto-3
    restart: always
    ports:
      - 1886:1883
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
  s1-dc:
    image: mqtt-php
    container_name: s1-dc
    restart: always
    volumes:
      - ./app1:/var/www/html/app
    command: php app/subscribe.php /erp/pedidos-recibidos
  s2-dc:
    image: mqtt-php
    container_name: s2-dc
    restart: always
    volumes:
      - ./app2:/var/www/html/app
    command: php app/subscribe.php /erp/pedidos-recibidos
